### PR TITLE
Adding the port to the hostname

### PR DESCRIPTION
**Pull request by ghost**
solves  #10

### CODE REVIEW

**Comment by nicholasamorim** [comment]
Not so sure about this change. It used to be like that but if I remember correctly several other places needed the hostname alone. I will take a deeper look at what caused my problem and see if this is suitable indeed or not.

**Comment by ghost** [comment]
Alright, let me know when you take time to check that :).
Here everything seems to work but I haven't tried notary for example.
Without that, http redirect doesn't work and docker push either

**Comment by nicholasamorim** [comment]
Yes! I'm looking into Molecule this week to add tests for this role so that we can track these issues and effects better.

**Comment by ghost** [comment]
@nicholasamorim 
Hi! :)
Any news on molecule? I haven't used it myself but if you need some help, I should have a bit more free time next month

**Comment by nicholasamorim** [comment]
Hey, @achrjulien, I haven't had time yet. I did check Molecule out but haven't had time to implement it for this role. 

The main reason being that I moved away from Harbor to Quay.io.  

If you can open a PR with tests, all the better. If not, I reckon it will take some time from my side.

**Comment by ghost** [comment]
Was there any test in particular you were thinking about? My time is quite limited as well lately :)

**Comment by nicholasamorim** [comment]
@achrjulien I suppose verify the installation is correct, all components are running on docker and ultimately check if users/projects were created.

**Comment by ghost** [comment]
Thanks! @nicholasamorim 
Got more work on the table for next month so I won't be able to help before July. If someone reads here and want to help, please do so :)

**Pull request merged**
